### ISSUE TITLE
How to calculate the mismatch rates across sliding windows of 20 Mb, moving by 1 Mb each step using the pMMRCalculator

### ISSUE THREAD

**Issue by zhangjsyeah** [TCLamnidis/pMMRCalculator#1]
Dear.Prof
Sorry to bother you, I want to calculate the mismatch rates across sliding windows of 20 Mb, moving by 1 Mb each step. but I don't know how to do it by using the pMMRCalculator. Can you give me some advices? Thanks a lot
you can refer to this article (A high-resolution picture of kinship practices in an Early Neolithic tomb  https://www.nature.com/articles/s41586-021-04241-4#article-info)

**Comment by TCLamnidis** [comment]
Hi Jiashuo!

pMMRCalculator does not support calculating pMMR in sliding windows. The authors of the paper must have used a different program for their calculations. 

[READ](https://bitbucket.org/tguenther/read/src/master/) might be able to do what you are attempting instead.
